reorder_imports = true
reorder_modules = true
newline_style = "Unix"
chain_width = 120
max_width = 120
# type_punctuation_density = "Wide"
# normalize_comments = true
# normalize_doc_attributes = true
# imports_granularity = "Module"